/* Generated by S-function Builder */
/* Copyright 2013 The MathWorks, Inc.*/
#ifndef _LINEAROUTPUTBUS_BUS_H_
#define _LINEAROUTPUTBUS_BUS_H_
/* Read only - STARTS */
#include "tmwtypes.h"




#ifndef _DEFINED_TYPEDEF_FOR_StatesBus_
#define _DEFINED_TYPEDEF_FOR_StatesBus_ 
typedef struct {
  real_T V_body[3];
  real_T Omega_body[3];
  real_T Euler[3];
  real_T Accel_body[3];
  real_T dOmega_body[3];
  real_T V_ned[3];
  real_T X_ned[3];
  real_T LLA[3];
  real_T DCM_be[9];
} StatesBus;
#endif

/* Read only - ENDS */


#endif
